### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by systemcrash** [gl-inet/mt798x-boot#3]
Can something be done about the `atf-20220606-637ba581b/makefile` and `atf-20220606-637ba581b/Makefile` name collision?

Also, are you certain it is:
`	cp ../uboot-mtk-20220606/u-boot.bin .`
and not
`	cp ../uboot-mtk-20220606/u-boot-mtk.bin .`
?

**Comment by alzhao** [comment]
it is u-boot.bin
